// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/servers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/servers">> = Specific
  const handler = {} as typeof import("../../app/admin/servers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ame/[ameId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ame/[ameId]">> = Specific
  const handler = {} as typeof import("../../app/ame/[ameId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ame/evolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ame/evolution">> = Specific
  const handler = {} as typeof import("../../app/ame/evolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ame/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ame">> = Specific
  const handler = {} as typeof import("../../app/ame/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/skills/browser-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/skills/browser-control">> = Specific
  const handler = {} as typeof import("../../app/skills/browser-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/servers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/servers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/servers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/multimodal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/multimodal">> = Specific
  const handler = {} as typeof import("../../app/api/ai/multimodal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/validate">> = Specific
  const handler = {} as typeof import("../../app/api/ai/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ame-core/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ame-core">> = Specific
  const handler = {} as typeof import("../../app/api/ame-core/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/anomalies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/anomalies">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/anomalies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/predictions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/predictions">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/predictions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discord/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discord/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/discord/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/status">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs">> = Specific
  const handler = {} as typeof import("../../app/api/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/ames/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/ames">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/ames/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/chat">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mobile/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/sync">> = Specific
  const handler = {} as typeof import("../../app/api/mobile/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/skills/browser-control/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills/browser-control">> = Specific
  const handler = {} as typeof import("../../app/api/skills/browser-control/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/slack/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slack/events">> = Specific
  const handler = {} as typeof import("../../app/api/slack/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/slack/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/slack/install">> = Specific
  const handler = {} as typeof import("../../app/api/slack/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/teams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teams">> = Specific
  const handler = {} as typeof import("../../app/api/teams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/telegram/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telegram/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/telegram/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
